config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'

  devise_for :users, path: "accounts", :controllers => { :omniauth_callbacks => 'users/omniauth_callbacks' }
  
  resources :posts do
    member do 
      post 'like'
      post 'unlike'
    end
  end
  
  get 'friends', to: 'users#index'
  resources :users, only: [:show] do
    post 'set_profile_picture', on: :member
  end
  
  resources :friend_requests, only: [:create, :destroy]
  resources :friendships, only: [:create, :destroy]
  resources :comments, only: [:create, :destroy]
end

app/models/user.rb
class User < ApplicationRecord
  before_save :capitalize_names
  after_create :send_welcome_email
  after_create :add_default_friends
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable
         
  has_many :posts, dependent: :destroy
  has_many :comments, foreign_key: "author_id", dependent: :destroy
  has_many :likes, dependent: :destroy

  has_many :friendships, dependent: :destroy   
  has_many :friends,  through: :friendships                              
  
  has_many :inverse_friendships, class_name: "Friendship", foreign_key: "friend_id", dependent: :destroy
  has_many :inverse_friends, through: :inverse_friendships, source: :user
  
  has_many :friend_requests_as_receiver, class_name: "FriendRequest", foreign_key: "receiver_id", dependent: :destroy
  has_many :friend_requests_as_requestor, class_name: "FriendRequest", foreign_key: "requestor_id", dependent: :destroy

  has_one_attached :profile_picture
  
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true, uniqueness: true

  devise :omniauthable, :omniauth_providers => [:facebook]

  def likes?(post)
    self.likes.any? {|like| like.post_id == post.id}
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session['devise.facebook_data'] && session['devise.facebook_data']['extra']['raw_info']
        user.email = data['email'] if user.email.blank?
      end
      end
    end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.first_name = auth.info.name.split.first
      user.last_name = auth.info.name.split.last 
    end
  end

  private

  def capitalize_names
    self.first_name = first_name.camelcase
    self.last_name = last_name.camelcase
  end

  def send_welcome_email
    UserMailer.welcome_email(self).deliver
  end

  def add_default_friends
    Friendship.create(user_id: self.id, friend_id: 0)
    Friendship.create(user_id: self.id, friend_id: 1)
    Friendship.create(user_id: self.id, friend_id: 2)
    Friendship.create(user_id: self.id, friend_id: 3)
    Friendship.create(user_id: self.id, friend_id: 4)    
  end
  
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.from_omniauth(request.env['omniauth.auth'])
    if @user.persisted?
      add_default_friends
      sign_in_and_redirect @user, :event => :authentication
      set_flash_message(:notice, :success, :kind => 'facebook') if is_navigational_format?
    else
      session['devise.facebook_data'] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end

 alias_method :passthru, :facebook

 private

 def add_default_friends
  if @user.friends.length == 0 
    Friendship.create(user_id: @user.id, friend_id: 0)
    Friendship.create(user_id: @user.id, friend_id: 1)
    Friendship.create(user_id: @user.id, friend_id: 2)
    Friendship.create(user_id: @user.id, friend_id: 3)
    Friendship.create(user_id: @user.id, friend_id: 4)    
  end
end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy, :set_profile_picture]
  before_action :authenticate_user!
  

  def index
    @user = current_user
    @user_friends = @user.friends + @user.inverse_friends

    @pending_requests_receiver_ids = []
    @user.friend_requests_as_requestor.each do |request|
      @pending_requests_receiver_ids << request.receiver_id
    end

    @pending_requests_requestor_ids = []
    @user.friend_requests_as_receiver.each do |request|
      @pending_requests_requestor_ids << request.requestor_id
    end

    @user_not_friends = User.all 
    @user_not_friends = @user_not_friends.reject {|user| @user_friends.include?(user) || @pending_requests_requestor_ids.include?(user.id)}
    @user_not_friends.delete(@user)

    @friend_request = FriendRequest.new
    @friendship = Friendship.new
  end

  def show
    @posts = current_user.posts
  end

  def set_profile_picture
    @user.profile_picture.attach(params[:profile_picture])
    redirect_to user_path(@user)
  end

  private

    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.fetch(:user, {})
    end

end

app/helpers/users/omniauth_callbacks_helper.rb
module Users::OmniauthCallbacksHelper
end

app/views/users/_picture_upload_form.html.erb
<%= form_with(url: set_profile_picture_user_path, local: true) do |form| %>
  <div class="actions">
    <%= form.label "Upload New Profile Picture?"%>
    <%= form.file_field :profile_picture%>
    <%= form.submit %>
  </div>
<% end %>

app/views/users/index.html.erb
<div id="friends-feed">
  <div id="friend-requests">
    <div class="heading">
      <h2>Friend Requests</h2>
    </div>
    <% @user.friend_requests_as_receiver.each do |request| %>
      <div class="request">
        <%= request.requestor.first_name %>
        <%= request.requestor.last_name %>
        <%= render 'friendships/accept_request_form', friendship: @friendship, request: request%>
      </div>
    <% end %>
  </div>
  <div id="friends">
    <div class="heading">
      <h2>Friends</h2>
    </div>
    <% @user_friends.each do |friend| %>
      <div class="friend">
        <%= friend.first_name %>
        <%= friend.last_name %>
      </div>
    <% end %>
  </div>
  <div id="not-friends">
    <div class="heading">
      <h2>Other Users</h2>
    </div>
    <% @user_not_friends.each do |friend| %>
      <div class="friend">
        <%= friend.first_name %>
        <%= friend.last_name %>
        <% if @pending_requests_receiver_ids.include?(friend.id) %>
          <span id="request-sent">(request sent)</span>
        <% else %>
          <%= render 'friend_requests/send_request_form', request: @friend_request, friend: friend %>
        <% end %>
      </div>
    <% end %>
  </div>
</div>
<br>

app/views/users/show.html.erb
<div id="profile-info">  
  
    <div id="profile-photo">
      <% if current_user.profile_picture.attached?%>
        <%= image_tag(url_for(current_user.profile_picture), :size => '260x180')%>
      <%end%>
      <% if !current_user.profile_picture.attached?%>
        <p> Upload a profile photo!</p>
      <%end%>
    </div>
    <div id="new-picture-links">
      <%= render 'picture_upload_form'%>
    </div>
  <div id="user-info">
    <%= "#{current_user.first_name} #{current_user.last_name}"%>
  </div>
</div>
<div id="posts">
  <% if @posts.length > 0%>
    <%= render 'posts/posts', posts: @posts%>
  <% else %>
    <p>Your Posts will show up here!</p>
  <% end %> 
</div>