config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'

  devise_for :users, path: "accounts", :controllers => { :omniauth_callbacks => 'users/omniauth_callbacks' }
  
  resources :posts do
    member do 
      post 'like'
      post 'unlike'
    end
  end
  
  get 'friends', to: 'users#index'
  resources :users, only: [:show] do
    post 'set_profile_picture', on: :member
  end
  
  resources :friend_requests, only: [:create, :destroy]
  resources :friendships, only: [:create, :destroy]
  resources :comments, only: [:create, :destroy]
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: "User", 
                      foreign_key: "user_id"
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  def index
    friend_ids = current_user.friends.pluck(:id)
    friend_ids += current_user.inverse_friends.pluck(:id) 
    @posts = Post.where(:user_id => current_user.id).or(Post.where(:user_id => friend_ids)).order(created_at: :desc) 
  end
  
  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to posts_path, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def like
    like = Like.new(post_id: params[:id], user_id: params[:user_id])

    unless like.already_exists?
      like.save
      post = Post.find(params[:id])
      post.like_count += 1
      post.save
    end
    redirect_to posts_path
  end

  def unlike
    like = Like.where(post_id: params[:id], user_id: params[:user_id]).take

    if like
      like.destroy
      post = Post.find(params[:id])
      post.like_count -= 1
      post.save
    end

    redirect_to posts_path
  end

  private
    
    def set_post
      @post = Post.find(params[:id])
    end

    def post_params
      params.require(:post).permit(:body, :user_id)
    end
end

app/views/posts/_comment_form.html.erb
<%= form_with(url: comments_path, method: :post) do |form|%>
  <%= form.text_area :body, style: "width:100%", placeholder: "Write a comment..."%>
  <%= form.hidden_field :post_id, value: post_id %>
  <%= form.hidden_field :author_id, value: author_id %>
  <%= form.submit "Comment"%>
<% end %>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.text_area :body, style: "30x10", placeholder: "What's on your mind?"%><br>
    <%= form.hidden_field :user_id, :value => current_user.id %>
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/_like_form.html.erb
<%= form_with(url: like_post_path(post_id), method: "post", local: true) do |form| %>
  <div class="actions">
    <%= form.hidden_field :user_id, :value => user_id %>
    <%= form.submit "Like"%>
  </div>
<% end %>

app/views/posts/_posts.html.erb
<% posts.each do |post| %>
    <div class="post">
      <div class="post-header">
        <div class="post-header-image"> 
          <% if post.author.profile_picture.attached?%>
            <%= image_tag(url_for(post.author.profile_picture), :size => '35x35')%>
          <%end%>
        </div>
        <span class="post-header-name">
        
          <%= post.author.first_name%> <%= post.author.last_name%>
        </span>
      </div>
      <div class="post-content">
        <%= post.body%>
      </div>
      <div class="post-likes">
        <%= "#{post.like_count} Likes"%>
      </div>
      <div class="like-post">
        <%= link_to_if(!current_user.likes?(post), 'Like?', like_post_path(post.id, user_id: current_user.id), method: :post) do 
            link_to '(Liked)', unlike_post_path(post.id, user_id: current_user.id), method: :post  
          end %>
      </div>
      <div class="post-comments">
        <div class="new-comment">
          <%= render 'posts/comment_form', author_id: current_user.id, post_id: post.id%>
        </div>
        <div class="existing-comments">
          <% post.comments.each do |comment|%>
            <div class="comment">
              <div class="comment-head">
                <%=comment.author.first_name%>
                <%=comment.author.last_name%>
              </div>
              <div class="comment-body">
                <%=comment.body%>
              </div>
            </div>
          <%end%>
        </div>
      </div>
    </div>
  <% end %>

app/views/posts/edit.html.erb
<div id="heading">  
  <h1>Edit Post</h1>
</div>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<div id="new-post">
  <%= link_to "What's on your mind?", new_post_path %>
</div>

<div id="feed">
  <%= render 'posts', posts: @posts %>
</div>
<br>

app/views/posts/new.html.erb
<div id="new-post-page">
  <h1>New Post</h1>

  <%= render 'form', post: @post %>

  <%= link_to 'Back', posts_path %>

</div>

app/views/posts/show.html.erb
<div id="post">
  <p>
    <%= @post.body%>
  </p>
</div>

<%= link_to 'Edit Post', edit_post_path(@post) %> |
<%= link_to 'Delete Post', @post, method: :delete, data: { confirm: 'Are you sure?' } %> |
<%= link_to 'Back', posts_path %>