config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'

  devise_for :users, path: "accounts", :controllers => { :omniauth_callbacks => 'users/omniauth_callbacks' }
  
  resources :posts do
    member do 
      post 'like'
      post 'unlike'
    end
  end
  
  get 'friends', to: 'users#index'
  resources :users, only: [:show] do
    post 'set_profile_picture', on: :member
  end
  
  resources :friend_requests, only: [:create, :destroy]
  resources :friendships, only: [:create, :destroy]
  resources :comments, only: [:create, :destroy]
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Fakebook</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
     <link href="https://fonts.googleapis.com/css2?family=Roboto&display=swap" rel="stylesheet"> 
    <link href='https://fonts.googleapis.com/css?family=Montserrat' rel='stylesheet'>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div id="body-container">
      <div id="user_nav">
        <% if user_signed_in? %>
          <div id="nav-content">
            <div>
            <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
            </div>
            <%= link_to "Home", root_path%>
            <%= link_to "Friends #{ "(#{current_user.friend_requests_as_receiver.count})" unless current_user.friend_requests_as_receiver.empty?}", friends_path%>
            <%= link_to "Profile", user_path(current_user.id)%>
          </div>
        <% end %>
      </div>

      <div id="flashes">
        <p class="notice"><%= notice %></p>
        <p class="alert"><%= alert %></p>
      </div>
      <%= yield %>
    </div>
  </body>
</html>